hossz = 30
def harc_eredmeny_kiir(fegyver:str,szorny:str, eredmeny:str):
    print("\033c")
    print(f"╔{'═'*(hossz)}╗")
    print(f"║{'★ A HARC EREDMÉNYE ★':^{hossz}}║")
    print(f"║{'-'*(hossz)}║")
    print(f"║{'A':^{hossz}}║")
    print(f"║{szorny:^{hossz}}║")
    print(f"║{'ellen harcoltál':^{hossz}}║")
    print(f"║{'-'*(hossz)}║")
    print(f"║{'A fegyvered':^{hossz}}║")
    print(f"║{fegyver:^{hossz}}║")
    print(f"║{'-'*(hossz)}║")
    print(f"║{eredmeny.upper():^{hossz}}║")
    print(f"╚{'═'*(hossz)}╝")